version: '3.4'

services:

  tornado_web:
    build: .
    container_name: tornado_web
    command: bash -c "exec invoke startTornadoApp"
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ".:/opt/tornado_skillup_proj"
    networks:
      - async-backend

  nginx:
    build: ./nginx
    container_name: nginx
    command: sh /etc/nginx/wait_for_other_services.sh
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "9999:9999"
    depends_on:
      - tornado_web
    networks:
      - async-backend


networks:
  async-backend: