version: '3.4'

services:
  tornado_web:
    image: tornado_proj_tornado_web
    command: bash -c "exec invoke startTornadoApp"
#    volumes:
#      - ".:/opt/tornado_skillup_proj"
    networks:
      - async-backend
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  nginx:
    image: tornado_proj_nginx
    command: sh /etc/nginx/wait_for_other_services.sh
    ports:
      - "8000:9999"
    depends_on:
      - tornado_web
    networks:
      - async-backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  async-backend: